### ISSUE TITLE
NullPointerException on breaking normal dispenser

### ISSUE THREAD

**Issue by N3bby** [chibill/AutoCrafters#1]
OS: Ubuntu 16.04.1 Server
Java version: 1.8.0_101
Spigot version: 1.11.2-R0.1-SNAPSHOT
AutoCrafters version: 1.3

The problem? :  Exception in the console upon breaking a normal dispenser

`[23:38:22] [Server thread/ERROR]: Could not pass event BlockBreakEvent to AutoCrafters v1.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:291) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:218) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:842) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
	at minecraft16.autocrafters.Events.onBreak(Events.java:53) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	... 17 more`

What you expect to happen: No exception

What actually happened: See problem description

Steps to reproduce.

  1. /give user dispenser 1
  2. Place down the dispenser
  3. Break the dispenser
  4. Exception will be thrown

**Comment by wgaylord** [comment]
Just fixed it. (Did not bump the version number but. Just released it.)
