### ISSUE TITLE
Help,sir

### ISSUE THREAD

**Issue by NewaSeven** [chibill/AutoCrafters#10]
MC Version : 1.10

Plugin Version : 1.6.0

The problem? : is the plugin ViaVersion, but the problem remains

[09:51:02] [Server thread/ERROR]: Could not pass event BlockDispenseEvent to AutoCrafters v1.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-72c2605-251a5b6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-72c2605-251a5b6]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-72c2605-251a5b6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.DispenseBehaviorItem.a(DispenseBehaviorItem.java:63) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.DispenseBehaviorItem.b(DispenseBehaviorItem.java:26) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.DispenseBehaviorItem.a(DispenseBehaviorItem.java:13) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.BlockDispenser.dispense(BlockDispenser.java:87) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.BlockDispenser.b(BlockDispenser.java:116) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.WorldServer.a(WorldServer.java:738) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.WorldServer.doTick(WorldServer.java:250) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:783) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [server.jar:git-Spigot-72c2605-251a5b6]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NoSuchMethodError: org.bukkit.block.Dispenser.getCustomName()Ljava/lang/String;
	at minecraft16.autocrafters.Events.onDespense(Events.java:121) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-72c2605-251a5b6]
	... 15 more

**Comment by wgaylord** [comment]
Can you please give me more details about your server. Example your spigot version? (Run /version)

Also I don’t believe 1.10 is supported currently but let me check

**Comment by wgaylord** [comment]
Also you appear to be running version 1.2 of AutoCrafter yet you say you are using 1.6.0

**Comment by NewaSeven** [comment]
On version 1.6.0

[11:41:04] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to AutoCrafters v1.6.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-72c2605-251a5b6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-72c2605-251a5b6]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-72c2605-251a5b6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-72c2605-251a5b6]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:146) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.ItemStack.placeItem(ItemStack.java:162) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:538) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:910) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-72c2605-251a5b6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [server.jar:git-Spigot-72c2605-251a5b6]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NoSuchMethodError: org.bukkit.block.Dispenser.getCustomName()Ljava/lang/String;
	at minecraft16.autocrafters.Events.onPlace(Events.java:34) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-72c2605-251a5b6]
	... 18 more
[11:41:09] [Server thread/INFO]: Stopping the server

**Comment by NewaSeven** [comment]
And even was higher


[11:39:56] [Server thread/ERROR]: Error occurred while enabling AutoCrafters v1.6.0 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/NamespacedKey
	at minecraft16.autocrafters.Main.onEnable(Main.java:81) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[server.jar:git-Spigot-72c2605-251a5b6]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-72c2605-251a5b6]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-72c2605-251a5b6]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373) [server.jar:git-Spigot-72c2605-251a5b6]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [server.jar:git-Spigot-72c2605-251a5b6]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [server.jar:git-Spigot-72c2605-251a5b6]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.ClassNotFoundException: org.bukkit.NamespacedKey
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[server.jar:git-Spigot-72c2605-251a5b6]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-72c2605-251a5b6]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	... 12 more

**Comment by NewaSeven** [comment]
I have is worth spigot-1.10.2-R0.1-SNAPSHOT

**Comment by wgaylord** [comment]
1.10 is not supported.

**Comment by wgaylord** [comment]
1.10 is not supported.
